
##########################################################
## user configuration
##########################################################

# PASS

#############################
# project-specific configuration
#############################

# Simply a tab
define bsg_var_tab
	
endef

# Simply a comma
bsg_var_comma := ,

bsg_fn_lst2csv = $(subst $(bsg_var_space),$(bsg_var_comma),$(strip $(1)))

# Searches up a dir tree for a specified matchfile
# ex: bsg_fn_find_dir_width .BSG_DESIGN
#   -> ../../
# Credit to stdavids
define bsg_var_find_dir_with
$(shell \
	d=$$(pwd); \
	while [ "$$d" != "/" ] && [ ! -e "$$d/$(1)" ]; do \
		d=$$(dirname "$$d"); \
	done; \
	[ -e "$$d/$(1)" ]; \
	echo "$$d" \
	)
endef

# Creates a standard directory tree at root
# ex: bsg_fn_create_subdirs BSG_PEARLS, TOP
#   -> BSG_PEARLS_MK_DIR := $(TOP)/mk
define bsg_fn_create_subdirs
	$(eval root_var := $(1))
	$(eval root_dir := $(2))
	$(eval $(root_var)_MK_DIR  := $(root_dir)/mk)
	$(eval $(root_var)_PY_DIR  := $(root_dir)/py)
	$(eval $(root_var)_SRC_DIR := $(root_dir)/v)
	$(eval $(root_var)_TCL_DIR := $(root_dir)/tcl)
	$(eval $(root_var)_TEST_DIR      := $(root_dir)/test)
	$(eval $(root_var)_TEST_MK_DIR   := $(root_dir)/test/mk)
	$(eval $(root_var)_TEST_PY_DIR   := $(root_dir)/test/py)
	$(eval $(root_var)_TEST_SRC_DIR  := $(root_dir)/test/v)
	$(eval $(root_var)_TEST_TCL_DIR  := $(root_dir)/test/tcl)
	$(eval $(root_var)_DC_DIR        := $(root_dir)/dc)
	$(eval $(root_var)_YOSYS_DIR     := $(root_dir)/yosys)
	$(eval $(root_var)_SURELOG_DIR   := $(root_dir)/surelog)
	$(eval $(root_var)_VCS_DIR       := $(root_dir)/vcs)
	$(eval $(root_var)_VERILATOR_DIR := $(root_dir)/verilator)
endef

# Define bsg_pearl IP toplevels
export BSG_PEARLS_DIR         ?= $(TOP)
export BSG_DESIGN_DIR         ?= $(call bsg_var_find_dir_with,.BSG_DESIGN)
export BSG_CLK_GEN_PEARL_DIR  ?= $(BSG_PEARLS_DIR)/bsg_clk_gen_pearl
export BSG_SDR_LINK_PEARL_DIR ?= $(BSG_PEARLS_DIR)/bsg_sdr_link_pearl
export BSG_DDR_LINK_PEARL_DIR ?= $(BSG_PEARLS_DIR)/bsg_ddr_link_pearl
export BSG_DMC_PEARL_DIR      ?= $(BSG_PEARLS_DIR)/bsg_dmc_pearl

# Other directories
BASEJUMP_STL_DIR       ?= $(BSG_PEARLS_DIR)/../basejump_stl

# Create the subdirectory structure
$(eval $(call bsg_fn_create_subdirs,BSG_PEARLS,$(BSG_PEARLS_DIR)))
$(eval $(call bsg_fn_create_subdirs,BSG_DESIGN,$(BSG_DESIGN_DIR)))
$(eval $(call bsg_fn_create_subdirs,BSG_CLK_GEN_PEARL,$(BSG_CLK_GEN_PEARL_DIR)))
$(eval $(call bsg_fn_create_subdirs,BSG_DMC_PEARL,$(BSG_DMC_PEARL_DIR)))
$(eval $(call bsg_fn_create_subdirs,BSG_SDR_LINK_PEARL,$(BSG_SDR_LINK_PEARL_DIR)))
$(eval $(call bsg_fn_create_subdirs,BSG_DDR_LINK_PEARL,$(BSG_DDR_LINK_PEARL_DIR)))

BSG_DESIGN  := $(shell cat $(BSG_DESIGN_DIR)/.BSG_DESIGN)
BSG_WRAPPER := bsg_chip

PDK ?= sky130A
PDK_LIB ?= sky130_fd_sc_hd
PDK_CORNER ?= tt_025C_1v80

BASEJUMP_STL_BETA_DIR ?= $(BSG_PEARLS_SRC_DIR)/basejump_stl_beta
BASEJUMP_STL_HARD_DIR ?= $(BASEJUMP_STL_BETA_DIR)/hard/sky_130

##########################################################
## utilities
##########################################################

AUTORECONF ?= autoreconf
AUTOCONF   ?= autoconf
AWK        ?= awk
BASENAME   ?= basename
CAT        ?= cat
CD         ?= cd
COLUMN     ?= column
CP         ?= cp
CURL       ?= curl
CUT        ?= cut
DIFF       ?= diff
ECHO       ?= echo
ENVSUBST   ?= envsubst
EXIT       ?= exit
FILE       ?= file
FIND       ?= find
GENHTML    ?= genhtml
GIT        ?= git
GREP       ?= grep
MKDIR      ?= mkdir
MKDIRP     ?= mkdir -p
MV         ?= mv
PRINTF     ?= printf
RM         ?= rm
RMRF       ?= rm -rf
SED        ?= sed
SORT       ?= sort
STTY       ?= stty
STRIP      ?= strip
SYMLINK    ?= ln -nsf
TAIL       ?= tail
TAR        ?= tar
TEE        ?= tee
TEST       ?= test
TOUCH      ?= touch
TR         ?= tr
UNIQ       ?= uniq
WCOUNT     ?= wc -l
WGET       ?= wget
XXD        ?= xxd

MORTY      ?= morty
VLOGAN     ?= vlogan
VHDLAN     ?= vhdlan
XRUN       ?= xrun
SIMVISION  ?= simvision
IMC        ?= imc
URG        ?= urg

