

# $(1) -> corner
build-%: ## builds a simulation (build-<CORNER>) for individual corner
define bsg_fn_verilator_build
ifndef $(0)$(1)
$(0)$(1) := DEFINED

$(1)BUILD_OPTS := $(VV_BUILD_OPTS)
ifeq ($(TRACE),1)
$(1)BUILD_OPTS += --trace --trace-structs --trace-fst
endif
$(1)BUILD_OPTS += $(addprefix +define+,$(VDEFINES) $(TEST_VDEFINES))

$(1)cfg := \
	$(wildcard $(BSG_PEARLS_SRC_DIR)/*.vlt) $(wildcard $(BSG_PEARLS_TEST_SRC_DIR)/*.vlt) \
	$(wildcard $(BSG_DESIGN_SRC_DIR)/*.vlt) $(wildcard $(BSG_DESIGN_TEST_SRC_DIR)/*.vlt)

$(1)/config.vlt: $$($(1)cfg)
	@$(ECHO) "\`verilator_config" >> $$@
	@$(CAT) $$^ >> $$@

$(1)/simsc: $(1)/config.vlt test/testbench.pickled.sv $(1)/wrapper.pickled.sv $(HARD_NSOURCES) $(PDK_NSOURCES)
	@$(MKDIR) -p $$(@D)
	@$(CD) $$(@D); \
		$(VERILATOR) $$($(1)BUILD_OPTS) $$(abspath $$^) | $(TEE) -i build.log
build-$(1): $(1)/simsc

clean::
	@$(RM) -rf $(1)/simsc
	@$(RM) -rf $(1)/obj_dir
	@$(RM) -rf $(1)/build.log
	@$(RM) -rf $(1)/config.vlt

endif
endef

VV_RUN_OPTS +=

# $(1) -> corner
# $(2) -> name
# $(3) -> tag trace
# $(4) -> test trace
define bsg_fn_verilator_sim

$(eval $(call bsg_fn_chip_gen,test))
$(eval $(call bsg_fn_chip_gen,$(1)))

$(eval $(call bsg_fn_pickle,test,testbench))
$(eval $(call bsg_fn_pickle,$(1),wrapper))

$(eval $(call bsg_fn_verilator_build,$(1)))

$(eval $(call bsg_fn_trace_gen,$(1)/$(2),$(3)))
$(eval $(call bsg_fn_trace_gen,$(1)/$(2),$(4)))

$(1)$(2)PLUSARGS += +TAG_TRACE=$(3).tr
$(1)$(2)PLUSARGS += +TEST_TRACE=$(4).tr

$(1)$(2)RUN_OPTS := $(VV_RUN_OPTS)

$(1)$(2)DUMPFILE := dump.fst
ifeq ($(ENABLE_SURFER),1)
$(1)$(2)VIEWCMD := $(SURFER) $$($(1)$(2)DUMPFILE)
else
$(1)$(2)VIEWCMD := $(GTKWAVE) -f $$($(1)$(2)DUMPFILE)
endif

ifeq ($(TRACE),1)
$(1)$(2)RUN_OPTS += +bsg_trace=$$($(1)$(2)DUMPFILE)
endif

$(1)/$(2)/run: $(1)/simsc $(1)/$(2)/$(3).tr $(1)/$(2)/$(4).tr
	@$(MKDIR) -p $$(@D)
	@$(CD) $$(@D); \
		../$$(<F) $$($(1)$(2)RUN_OPTS) $$($(1)$(2)PLUSARGS) | $(TEE) -i run.log
run-$(1)-$(2): $(1)/$(2)/run

$(1)/$(2)/view: $(1)/$(2)/$$($(1)$(2)DUMPFILE)
	@$(CD) $$(@D); \
		$$($(1)$(2)VIEWCMD) $$(<F) &
view-$(1)-$(2): $(1)/$(2)/view

clean::
	@$(RM) -rf $(1)/$(2)/run.log
	@$(RM) -rf $(1)/$(2)/$(3).tr
	@$(RM) -rf $(1)/$(2)/$(4).tr
	@$(RM) -rf $(1)/$(2)/$$($(1)$(2)DUMPFILE)
endef

VERILATOR_THREADS ?= 4
#VV_BUILD_OPTS += --debug --gdbbt --no-debug-leak
VV_BUILD_OPTS += --binary
VV_BUILD_OPTS += -O2
VV_BUILD_OPTS += --x-assign fast --x-initial fast
VV_BUILD_OPTS += -j $(VERILATOR_THREADS)
VV_BUILD_OPTS += --timescale 1ps/1ps
VV_BUILD_OPTS += -Wno-WIDTHEXPAND
VV_BUILD_OPTS += -Wno-MISINDENT
VV_BUILD_OPTS += --waiver-output test.waiver
# Part of synth flow
#VV_BUILD_OPTS += -Wno-MODDUP
#VV_BUILD_OPTS += -Wno-REDEFMACRO
#VV_BUILD_OPTS += -Wno-PINMISSING
#VV_BUILD_OPTS += -Wno-COMBDLY
#VV_BUILD_OPTS += -Wno-LATCH
# https://github.com/verilator/verilator/pull/6241
VV_BUILD_OPTS += --assert --no-stop-fail
VV_BUILD_OPTS += --stats --stats-vars
VV_BUILD_OPTS += --top-module testbench
#VV_BUILD_OPTS += --top-module testbench
VV_BUILD_OPTS += -o ../simsc

$(eval $(call bsg_fn_verilator_build,vlog,testbench,wrapper))
$(eval $(call bsg_fn_verilator_build,hard,testbench,wrapper))

