
# $(1) -> synthesis tag
define bsg_fn_yosys_synth

$(1)opts := $(YOSYS_OPTS)
$(1)opts += $$(addprefix -p "tcl ,$$(addsuffix ",$$($(1)_SCRIPTS)))
ifdef $(1)_SHELL
$(1)opts += -C
endif

$(1)/%.tcl: $(BSG_PEARLS_TCL_DIR)/%.tcl
	@$(CP) $$< $$@

$(1)/synth: $$(addprefix $(1)/,$$($(1)_SCRIPTS)) syn/wrapper.pickled.sv
	@$(MKDIR) -p $$(@D)
	@$(CD) $$(@D); \
		$(YOSYS) $$($(1)opts)
synth-$(1): $(1)/synth

clean::
	@$(RM) -rf $(1)/synth.log
	@$(RM) -rf $$(addprefix $(1)/,$$($(1)_SCRIPTS))
	@$(RM) -rf $(1)/$(BSG_DESIGN).*.v
	@$(RM) -rf $(1)/$(BSG_DESIGN).*.txt
	@$(RM) -rf $(1)/$(BSG_DESIGN).*.json

endef

YOSYS_OPTS += -m slang
YOSYS_OPTS += -l synth.log

basic_SCRIPTS    := bsg_pearls_setup.tcl bsg_design_setup.tcl bsg_chip_pkg.tcl bsg_utils.tcl yosys_utils.tcl synthesis.yosys.tcl
basic_LOGLEVEL   := 2

debug_SCRIPTS    := bsg_pearls_setup.tcl bsg_design_setup.tcl bsg_chip_pkg.tcl bsg_utils.tcl yosys_utils.tcl synthesis.yosys.tcl
debug_LOGLEVEL   := 3
debug_SHELL      := DEFINED

iterate_SCRIPTS  := bsg_pearls_setup.tcl bsg_design_setup.tcl bsg_chip_pkg.tcl bsg_utils.tcl yosys_utils.tcl
iterate_LOGLEVEL := 99
iterate_SHELL    := DEFINED

$(eval $(call bsg_fn_yosys_synth,basic))
$(eval $(call bsg_fn_yosys_synth,debug))
$(eval $(call bsg_fn_yosys_synth,iterate))

