
# $(1) -> synthesis tag
define bsg_fn_dc_synth

$(1)opts := $(DC_OPTS)
$(1)opts += -x "$$(foreach s,$$($(1)_SCRIPTS),source -verbose -echo $$(s);)
ifndef $(1)_SHELL
$(1)opts += exit;
endif
$(1)opts += "

$(1)/%.tcl: $(BSG_PEARLS_TCL_DIR)/%.tcl
	@$(CP) $$< $$@

$(1)/synth: $$(addprefix $(1)/,$$($(1)_SCRIPTS)) syn/wrapper.pickled.sv

	$(CD) $$(@D); \
		$(DC_SHELL) $$($(1)opts)
synth-$(1): $(1)/synth

clean::
	@$(RM) -rf $(1)/synth.log
	@$(RM) -rf $$(addprefix $(1)/,$$($(1)_SCRIPTS))
	@$(RM) -rf $(1)/default.svf
	@$(RM) -rf $(1)/command.log
	@$(RM) -rf $(1)/lc_shell_command.log
	@$(RM) -rf $(1)/filenames.log
	@$(RM) -rf $(1)/WORK/
	@$(RM) -rf $(1)/alib-*/
	@$(RM) -rf $(1)/$(BSG_DESIGN).*.v
	@$(RM) -rf $(1)/$(BSG_DESIGN).*.txt
	@$(RM) -rf $(1)/$(BSG_DESIGN).*.json
	@$(RM) -rf $(1)/$(BSG_DESIGN).*.rpt

endef

DC_OPTS += -64bit
DC_OPTS += -output_log_file synth.log

basic_SCRIPTS    := bsg_pearls_setup.tcl bsg_design_setup.tcl bsg_chip_pkg.tcl bsg_utils.tcl dc_utils.tcl synthesis.dc.tcl

debug_SCRIPTS    := bsg_pearls_setup.tcl bsg_design_setup.tcl bsg_chip_pkg.tcl bsg_utils.tcl dc_utils.tcl synthesis.dc.tcl
debug_SHELL      := DEFINED

iterate_SCRIPTS  := bsg_pearls_setup.tcl bsg_design_setup.tcl bsg_chip_pkg.tcl bsg_utils.tcl dc_utils.tcl
iterate_SHELL    := DEFINED

$(eval $(call bsg_fn_dc_synth,basic))
$(eval $(call bsg_fn_dc_synth,debug))
$(eval $(call bsg_fn_dc_synth,iterate))

