
# $(1) -> parse tag
define bsg_fn_surelog_parse

$(eval $(call bsg_fn_chip_gen,src))

$(eval $(call bsg_fn_pickle,src,wrapper))

$(1)opts := $(SURELOG_OPTS)
$(1)opts += $(addprefix +define+,$(VDEFINES))

$(1)/parse: syn/wrapper.pickled.sv
	@$(MKDIR) -p $$(@D)
	@$(CD) $$(@D); \
		$(SURELOG) $$($(1)opts) $$(abspath $$^)
parse-$(1): $(1)/parse

generate-$(1): $(1)/generate

$(1)/generate: $(1)/parse
	@$(CD) $$(@D); \
		$(PYTHON) $(BSG_PEARLS_PY_DIR)/bsg_chip_info.py slpp_unit/surelog.uhdm

clean::
	@$(RM) -rf $(1)/parse.log
	@$(RM) -rf $(1)/slpp_unit

endef

SURELOG_OPTS += -sverilog
SURELOG_OPTS += -fileunit
SURELOG_OPTS += -parse
SURELOG_OPTS += -verbose
SURELOG_OPTS += -elabuhdm
SURELOG_OPTS += --top-module wrapper
SURELOG_OPTS += -l ../parse.log

$(eval $(call bsg_fn_surelog_parse,basic))

