
# $(1) -> corner
define bsg_fn_vcs_build

$(1)vhdlsrc := $$(filter %.vhd %.vhdl,$$($(1)_SOURCES))
$(1)svsrc   := $$(filter %.v %.sv,$$($(1)_SOURCES))

$(1)/simv: $$($(1)_SOURCES) test/testbench.pickled.sv
	@echo "SOURCES $$($(1)_SOURCES)"
	@echo "VHDL $$($(1)vhdlsrc)"
	@echo "SV $$($(1)svsrc)"

$(1)-nothing:
	$(CD) $$(@D); \
		$(VHDLAN) $(VHDLAN_OPTS) $$($(1)vhdlsrc) -l vhdlan.log
	$(CD) $$(@D); \
		$(VLOGAN) $(VLOGAN_OPTS) $$($(1)svsrc) -l vlogan.log
	$(CD) $$(@D); \
		$(VCS) $(VCS_OPTS) -l build.log
build-$(1): $(1)/simv

clean::
	@$(RM) -rf $(1)/simv
	@$(RM) -rf $(1)/simv.daidir
	@$(RM) -rf $(1)/csrc
	@$(RM) -rf $(1)/vc_hdrs.h
	@$(RM) -rf $(1)/AN.DB
	@$(RM) -rf $(1)/64
	@$(RM) -rf $(1)/vlogan.log
	@$(RM) -rf $(1)/vhdlan.log
	@$(RM) -rf $(1)/build.log

endef

# $(1) -> corner
# $(2) -> name
# $(3) -> tag trace
# $(4) -> test trace
define bsg_fn_vcs_sim

$(eval $(call bsg_fn_trace_gen,$(1)/$(2),$(3)))
$(eval $(call bsg_fn_trace_gen,$(1)/$(2),$(4)))

$(1)$(2)plusargs += +TAG_TRACE=$(3).tr
$(1)$(2)plusargs += +TEST_TRACE=$(4).tr

$(1)$(2)runopts := $(SIMV_OPTS)

ifeq ($(ENABLE_VERDI),1)
$(1)$(2)dumpfile := dump.fsdb
$(1)$(2)viewcmd := $(VERDI) -ssf $$($(1)$(2)dumpfile)
else
$(1)$(2)dumpfile := dump.vpd
$(1)$(2)viewcmd := $(DVE) -full64 -vpd $$($(1)$(2)dumpfile)
endif

ifeq ($(TRACE),1)
$(1)$(2)runopts += +bsg_trace=$$($(1)$(2)dumpfile)
endif

$(1)/$(2)/run: $(1)/simv $(1)/$(2)/$(3).tr $(1)/$(2)/$(4).tr
	@$(MKDIR) -p $$(@D)
	@$(CD) $$(@D); \
		../$$(<F) $$($(1)$(2)runopts) $$($(1)$(2)plusargs) -l run.log
run-$(1)-$(2): $(1)/$(2)/run

$(1)/$(2)/view: $(1)/$(2)/$$($(1)$(2)dumpfile)
	@$(CD) $$(@D); $$($(1)$(2)viewcmd) $$($(1)$(2)dumpfile) &
view-$(1)-$(2): $(1)/$(2)/view

clean::
	@$(RM) -rf $(1)/$(2)/run.log
	@$(RM) -rf $(1)/$(2)/ucli.key
	@$(RM) -rf $(1)/$(2)/$(3).tr
	@$(RM) -rf $(1)/$(2)/$(4).tr
	@$(RM) -rf $(1)/$(2)/$$($(1)$(2)dumpfile)

endef

SIMLIB += $(filter-out %_sim.vhd,$(wildcard $(VCS_HOME)/packages/gtech/src/*.vhd))
SIMLIB += $(filter     %_sim.vhd,$(wildcard $(VCS_HOME)/packages/gtech/src/*.vhd))

VHDLAN_OPTS += -full64
VHDLAN_OPTS += -vhdl08
VHDLAN_OPTS += -verbose

VLOGAN_OPTS += -full64
VLOGAN_OPTS += -notice
VLOGAN_OPTS += -sverilog +v2k
VLOGAN_OPTS += -timescale=1ps/1ps
VLOGAN_OPTS += $(addprefix +define+,$(VDEFINES) $(TEST_VDEFINES))
VLOGAN_OPTS += -V

ifeq ($(ENABLE_VERDI),1)
VLOGAN_OPTS += -kdb
endif

ifeq ($(TRACE),1)
VCS_OPTS += -debug_access+r
endif

VCS_OPTS += -full64
VCS_OPTS += +noportcoerce
VCS_OPTS += +nospecify +notimingcheck
VCS_OPTS += +vcs+loopdetect
VCS_OPTS += -ignore initializer_driver_checks
VCS_OPTS += -V
VCS_OPTS += -top testbench
VCS_OPTS += -o simv

vlog_SOURCES := vlog/wrapper.pickled.sv
hard_SOURCES := hard/wrapper.pickled.sv $(HARD_NSOURCES)
syn_SOURCES := $(BSG_DESIGN_DC_DIR)/basic/$(BSG_DESIGN).wrapper.v $(HARD_NSOURCES)
syn-elab_SOURCES := $(syn_SOURCES) $(BSG_DESIGN_DC_DIR)/basic/$(BSG_DESIGN).elab.v

SIMV_OPTS += -no_save
#SIMV_OPTS += +vcs+loopdetect

$(eval $(call bsg_fn_vcs_build,vlog))
$(eval $(call bsg_fn_vcs_build,hard))
$(eval $(call bsg_fn_vcs_build,syn-elab))
#$(eval $(call bsg_fn_vcs_build,syn-gen))
#$(eval $(call bsg_fn_vcs_build,syn-opt))
#$(eval $(call bsg_fn_vcs_build,syn-tech))
#$(eval $(call bsg_fn_vcs_build,syn-final))

