
TEST_VDEFINES += FUNCTIONAL
TEST_VDEFINES += BSG_NO_TIMESCALE

TEST_VSOURCES += $(BSG_PEARLS_TEST_SRC_DIR)/bsg_nonsynth_test_rom_plusargs.sv
TEST_VSOURCES += $(BSG_PEARLS_TEST_SRC_DIR)/bsg_nonsynth_waveform_tracer.sv
TEST_VSOURCES += $(BSG_PEARLS_TEST_SRC_DIR)/bsg_nonsynth_assert.sv
TEST_VSOURCES += $(BSG_PEARLS_TEST_SRC_DIR)/bsg_chip_tester.sv
TEST_VSOURCES += $(BSG_PEARLS_TEST_SRC_DIR)/testbench.sv

SIMLIB += $(PDK_ROOT)/$(PDK)/libs.ref/$(PDK_LIB)/verilog/$(PDK_LIB).v
SIMLIB += $(BSG_PEARLS_TEST_SRC_DIR)/primitives.v

vlog_LIBLISTS := vpkg vlog test
hard_LIBLISTS := vpkg vpdk hard vlog test

define bsg_fn_config_gen

work/vpdk/flist.txt: $$(SIMLIB) | $$(VINCLUDES)
work/vpkg/flist.txt: $$(VPKG) | $$(VINCLUDES)
work/vlog/flist.txt: $$(VSOURCES) | $$(VINCLUDES)
work/test/flist.txt: $$(TEST_VSOURCES) | $$(VINCLUDES) $$(TEST_VINCLUDES)
work/hard/flist.txt: $$(HARD_VSOURCES) $$(HARD_NSOURCES) | $$(VINCLUDES) $$(HARD_VINCLUDES)

LIBMAP_CORNERS := vpdk vpkg vlog test hard
LIBMAP_FLISTS := $$(foreach x,$$(LIBMAP_CORNERS),work/$$(x)/flist.txt)

BUILD_SOURCES += $$(LIBMAP_FLISTS)

%/flist.txt:
	@$(MKDIR) -p $$(@D)
	@$(ECHO) "-work $$(@D:work/%=%)lib" > $$@;
	@for item in $$(VDEFINES) $$(TEST_VDEFINES) $$(HARD_VDEFINES); do \
		$(ECHO) "+define+$$$$item" >> $$@; \
	done
	@for item in $$|; do \
		$(ECHO) "+incdir+`realpath --relative-to=$(CURDIR)/work $$$$item`" >> $$@; \
	done
	@for item in $$(abspath $$^); do \
		$(ECHO) "$$(@D:work/%=%)/`basename $$$$item`" >> $$@; \
		$(SYMLINK) "$$$$item" $$(@D)/; \
	done

clean::
	@$(RMRF) work/vpdk
	@$(RMRF) work/vpkg
	@$(RMRF) work/vlog
	@$(RMRF) work/test
	@$(RMRF) work/hard

endef

