import argparse
import os


class BsgChipObject(object):
    def clog2(val):
        return (val - 1).bit_length()

    def __init__(self, name, desc=""):
        self.name = name
        self.desc = desc
        self.lineage = None
        self.width = None
        self.offset = None

    def __repr__(self):
        rstr = ""
        rstr += f"\t// Description: {self.desc}\n"

        return rstr

    def add(self, obj):
        self.__dict__[obj.name] = obj

        self.update_widths()

        return self

    def update_widths(self):
        self.width = 0
        for p in self.gen_clients():
            self.width += p.width

    def update_offsets(self, base):
        self.offset = base

        offset = self.offset
        for p in self.gen_clients():
            p.offset = offset
            offset += 1

    def update_lineage(self, current):
        for a, f in self.__dict__.items():
            if isinstance(f, BsgChipTagClientGroupObject):
                f.update_lineage(current + [self.name])
            elif isinstance(f, BsgChipTagClientObject):
                f.lineage = current + [self.name]

    def gen_params(self):
        for a, f in self.__dict__.items():
            if isinstance(f, BsgChipParamObject):
                yield f

    def gen_groups(self):
        for a, f in self.__dict__.items():
            if isinstance(f, BsgChipTagClientGroupObject):
                yield from f.gen_groups()
                yield f

    def gen_clients(self):
        for a, f in self.__dict__.items():
            if isinstance(f, BsgChipTagClientObject):
                yield f
            elif isinstance(f, BsgChipTagClientGroupObject):
                yield from f.gen_clients()

    def gen_imports(self):
        for a, f in self.__dict__.items():
            if isinstance(f, BsgChipImportObject):
                yield f


class BsgChipImportObject(BsgChipObject):
    def __repr__(self):
        rstr = ""
        if self.desc:
            rstr += f"\t// Description: {self.desc}\n"
        rstr += f"\timport {self.name}_pkg::*;\n"

        return rstr


class BsgChipParamObject(BsgChipObject):
    def __init__(self, name, val, desc=""):
        super().__init__(name, desc)
        self.val = val

    def __repr__(self):
        rstr = ""
        if self.desc:
            rstr += f"\t// Description: {self.desc}\n"
        rstr += f"\tlocalparam {self.name}_gp = {self.val};\n"

        return rstr

    def __int__(self):
        return self.val

class BsgChipTagClientObject(BsgChipObject):
    def __init__(self, name, width, desc=""):
        super().__init__(name, desc)

        self.struct = "bsg_tag"
        self.width = width
        # Updated by explicit command
        self.offset = None

    def __repr__(self):
        rstr = ""
        if self.desc:
            rstr += f"\t// Description: {self.desc}\n"
        rstr += f"\tbsg_tag_s {self.name}; // Local: {self.offset} Width: {self.width}\n"

        return rstr


class BsgChipTagClientGroupObject(BsgChipObject):
    def __init__(self, struct, name, desc="", external=False):
        super().__init__(name, desc)
        self.struct = struct
        self.external = external
        self.local_els_var = f"tag_{self.struct}_local_els_gp"
        self.width = None

    def __repr__(self):
        rstr = ""
        if self.desc:
            rstr += f"\t// Description: {self.desc}\n"
        rstr += f"\t"
        rstr += f"typedef struct packed\n"
        rstr += f"\t{{\n"
        for a, f in reversed(self.__dict__.items()):
            if isinstance(f, BsgChipObject):
                rstr += f"\t\t{f.struct}_s {f.name}; // Width: {f.width}\n"
        rstr += f"\t}} {self.struct}_s;\n"
        rstr += f"\tlocalparam {self.local_els_var} = $bits({self.struct}_s)/$bits(bsg_tag_s);\n"
        rstr += f"\n"

        return rstr


class BsgChipPkgObject(BsgChipObject):
    def __init__(self, name, struct, desc=""):
        super().__init__(name, desc)
        self.struct = struct

    def add(self, obj):
        super().add(obj)

        self.update_offsets(0)
        self.update_lineage([])

    def get_autogen(self, cs):
        vstr = ""
        vstr += f"\t{cs} Autogenerated by {os.path.basename(__file__)}: DO NOT MODIFY\n"
        vstr += f"\t{cs} Description: {self.desc}                                    \n"
        vstr += f"\t{cs}                                                             \n"

        return vstr

    def get_svhbody(self):
        vstr = ""

        vstr += f"\t`include \"bsg_defines.sv\"\n"
        vstr += f"\t`include \"bsg_tag.svh\"\n"
        # TODO: Add user hook

        return vstr

    def get_pkgbody(self):
        vstr = ""

        vstr += f"\t////////////////////////////////////////////////////////////////\n"
        vstr += f"\t// Includes                                                     \n"
        vstr += f"\t////////////////////////////////////////////////////////////////\n"

        vstr += f"\t////////////////////////////////////////////////////////////////\n"
        vstr += f"\t// Pkgs                                                         \n"
        vstr += f"\t////////////////////////////////////////////////////////////////\n"
        vstr += f"\t// Default packages                                             \n"
        vstr += f"\timport bsg_tag_pkg::*;                                          \n"
        for i in self.gen_imports():
            vstr += str(i)
        vstr += f"\n"

        vstr += f"\t////////////////////////////////////////////////////////////////\n"
        vstr += f"\t// Params                                                       \n"
        vstr += f"\t////////////////////////////////////////////////////////////////\n"
        for p in self.gen_params():
            vstr += str(p)
        vstr += f"\n"

        vstr += f"\t////////////////////////////////////////////////////////////////\n"
        vstr += f"\t// Tag Groups                                                   \n"
        vstr += f"\t////////////////////////////////////////////////////////////////\n"
        groups = [
            g
            for g in self.__dict__.values()
            if isinstance(g, BsgChipTagClientGroupObject)
        ]
        for g in groups:
            vstr += str(g)

        vstr += f"\t////////////////////////////////////////////////////////////////\n"
        vstr += f"\t// Virtual Tag Address Space                                    \n"
        vstr += f"\t////////////////////////////////////////////////////////////////\n"
        vstr += f"\t// This structure doesn't exist in reality, but is placed here  \n"
        vstr += f"\t//\tas a reference. Users should refer to the offsets           \n"
        vstr += f"\t//\tbelow to configure bsg_tag_master_decentralized             \n"
        vstr += f"\t//                                                              \n"
        vstr += f"\t//typedef struct packed {{                                      \n"
        for p in reversed(groups):
            vstr += f"\t//\t{p.struct}_s {p.name}; // {p.width}\n"
        vstr += f"\t//}} {self.struct}_s;\n"
        vstr += f"\n"

        prev = None
        offset_val = f"0"
        offset_var = f""
        offset_total = 0
        for p in groups:
            if prev:
                offset_val = f"{offset_var} + {prev.local_els_var}"
            else:
                offset_val = f"0"
            offset_var = f"tag_{p.name}_offset_gp"
            vstr += f"\tlocalparam {offset_var} = {offset_val}; // {offset_total} \n"
            offset_total += p.width
            prev = p
        vstr += f"\n"

        return vstr

    def get_pkgdef(self):
        vstr = self.get_autogen(cs='//')

        guard = f"{self.struct.upper()}DEF_SVH"
        vstr += f"`ifndef {guard}\n"
        vstr += f"`define {guard}\n"
        vstr += f"\n"

        #vstr += self.get_svhbody()
        #vstr += f"\n"
        vstr += self.get_pkgbody()

        vstr += f"\n"
        vstr += f"`endif // {guard}\n"
        vstr += f"\n"

        return vstr

    def get_pkg(self):
        vstr = self.get_autogen(cs='//')
        vstr += f"package {self.struct}_pkg;\n"

        vstr += self.get_svhbody()
        vstr += f"\n"
        vstr += self.get_pkgbody()
        vstr += f"\n"

        vstr += f"endpackage\n"
        vstr += f"\n"

        return vstr

    def get_svheader(self):
        vstr = self.get_autogen(cs='//')

        guard = f"{self.struct.upper()}_SVH"
        vstr += f"`ifndef {guard}\n"
        vstr += f"`define {guard}\n"
        vstr += f"\n"

        vstr += self.get_svhbody()

        vstr += f"\n"
        vstr += f"`endif // {guard}\n"
        vstr += f"\n"

        return vstr

    def get_tcl(self):
        vstr = self.get_autogen(cs='#')

        # Yosys runs tcl scripts in a subprocess, so variables must be generated by proc.
        # For example, set DESIGN will not be visible in the sourcing scope.
        # So we set them as environment variables

        vstr += f"set ::env(GPARAMS) [list \\\n"
        for p in self.gen_params():
            vstr += f"\t{p.name}_gp {p.val} \\\n"
        vstr += f"]\n"

        return vstr

    def get_cheader(self):
        guard = f"{self.struct.upper()}_H"

        vstr = self.get_autogen(cs='//')
        vstr += f"#ifndef {guard}\n"

        for g in [g for g in self.__dict__.values() if isinstance(g, BsgChipTagClientGroupObject)]:
            vstr += f"\t\n"
            vstr += f"\t///////////////////////////////////////////////////\n"
            vstr += f"\t// Tag Group Clients {g.name.upper()}\n"
            vstr += f"\t///////////////////////////////////////////////////\n"
            #clients = [c for c in g.__dict__.values() if isinstance(c, BsgChipTagClientObject)]
            for c in g.gen_clients():
                vstr += f"\t#define {self.struct.upper()}"
                for s in c.lineage[1:]:
                    vstr += f"_{s.upper()}"
                vstr += f"_{c.name.upper()}_OFFSET {c.offset}\n"

        vstr += f"\n"
        vstr += f"#endif // {guard}\n"
        vstr += f"\n"

        return vstr

if __name__ == "__main__":
    pkgdef = (
        BsgChipPkgObject("bsg_tag", "bsg_tag", "A package for bsg_tag")
        .add(BsgChipParamObject("test_param1", 3, "some_desc"))
        .add(BsgChipParamObject("test_param2", 2))
        .add(BsgChipImportObject("test1", "package_desc"))
        .add(BsgChipImportObject("test2"))
        .add(
            BsgChipTagClientGroupObject("group1", "g1", "group_desc")
            .add(BsgChipTagClientObject("client_1", 1, "client_desc"))
            .add(BsgChipTagClientObject("client_2", 2))
            .add(
                BsgChipTagClientGroupObject("subgroup1", "sg1").add(
                    BsgChipTagClientObject("client_6", 1)
                )
            )
            .add(
                BsgChipTagClientGroupObject(
                    "subgroup2", "sg2", external=True
                )
            )
        )
        .add(
            BsgChipTagClientGroupObject("group2", "g2")
            .add(BsgChipTagClientObject("client_3", 5, "client3_desc"))
            .add(BsgChipTagClientObject("client_4", 11))
        )
    )

    print(pkgdef.get_tcl())
