
import sys

num_rows_p = int(sys.argv[1])
num_cols_p = int(sys.argv[2])
num_dly_p  = int(sys.argv[3])

num_taps_p = num_rows_p*num_cols_p

print(f"""
// ## AUTOGENERATED; DO NOT MODIFY
// ## num_rows_p = {num_rows_p}
// ## num_cols_p = {num_cols_p}
// ## num_dly_p = {num_dly_p}
""")

print(f"""

module bsg_rp_clk_gen_osc_v3
  (input async_reset_i
   , input trigger_i
   , input [{num_taps_p-1}:0] ctl_one_hot_i
   , output clk_o
   );
  wire lobit, hibit;
  sky130_fd_sc_hd__conb_1 T0 (.HI(hibit), .LO(lobit));
  wire async_reset_neg;
  sky130_fd_sc_hd__inv_1 I0 (.Y(async_reset_neg), .A(async_reset_i));
  wire fb_inv, fb, fb_rst;
  sky130_fd_sc_hd__clkinv_1 I1 (.Y(fb_inv), .A(fb));

  sky130_fd_sc_hd__nand2_1 N0 (.Y(fb_rst), .A(fb_inv), .B(async_reset_neg));
  wire [{num_dly_p}:0] n;
  assign n[0] = fb_rst;
""")
for i in range(0, num_dly_p):
    print(f"""
    sky130_fd_sc_hd__clkbuf_2 B{i} (.X(n[{i+1}]), .A(n[{i}]));
""")
print(f"""
  wire fb_pre;
  sky130_fd_sc_hd__clkbuf_4 B{num_dly_p}_BSG_TIMING_DISABLE (.X(fb_pre), .A(n[{num_dly_p}]));
  wire fb_dly;
`ifdef SYNTHESIS
  assign fb_dly = fb_pre;
`else
  assign #`BSG_RP_CLK_GEN_OSC_SIM_DELAY fb_dly = fb_pre;
`endif
  sky130_fd_sc_hd__clkinv_4 I2 (.Y(clk_o), .A(fb_dly));
  wire fb_gate;
  sky130_fd_sc_hd__clkinv_4 I3 (.Y(fb_gate), .A(fb_dly));
  wire gate_en_sync_1_r, gate_en_sync_2_r;
  sky130_fd_sc_hd__dfrtp_1 D0_BSG_SYNC1 (.RESET_B(async_reset_neg), .D(trigger_i), .CLK(fb_gate), .Q(gate_en_sync_1_r));
  sky130_fd_sc_hd__dfrtp_1 D1_BSG_SYNC2 (.RESET_B(async_reset_neg), .D(gate_en_sync_1_r), .CLK(fb_gate), .Q(gate_en_sync_2_r));

  wire fb_gated;
  // Size to 1/4 of number of taps
  sky130_fd_sc_hd__dlclkp_1 CG0 (.GCLK(fb_gated), .CLK(fb_gate), .GATE(gate_en_sync_2_r));
  wire [{num_cols_p}:0] fb_col;
  assign fb_col[0] = 1'b0;
""")
for i in range(0, num_cols_p):
    print(f"""
      bsg_rp_clk_gen_osc_v3_col col_{i}_BSG_DONT_TOUCH
       (.async_reset_i(async_reset_i)
        ,.clkgate_i(fb_gated)
        ,.clkdly_i(fb_dly)
        ,.clkfb_i(fb_col[{i}])
        ,.ctl_one_hot_i(ctl_one_hot_i[{(i+1)*num_rows_p-1}:{i*num_rows_p}])
        ,.clk_o(fb_col[{i+1}])
        );
""")
print(f"""
  assign fb = fb_col[{num_cols_p}];
endmodule
""")
