
VPKG += bsg_chip_pkg.sv
bsg_chip_pkg.sv: %.sv: $(BSG_DESIGN_PY_DIR)/%.py
	PYTHONPATH=$(<D) \
		$(PYTHON) -c "from bsg_chip_pkg import BsgLinkPearlPkg; print(BsgClkGenPearlPkg().get_pkg())" \
	> $@
clean::
	@$(RMRF) bsg_chip_pkg.sv
VSOURCES += $(BSG_DESIGN_TEST_SRC_DIR)/bsg_chip.sv

HARD_VSOURCES += $(BASEJUMP_STL_HARD_DIR)/bsg_async/bsg_launch_sync_sync.sv
